[project]
name = "pydantic-ai-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-ai>=1.9.1",
]

[project.optional-dependencies]
dev = [
    "pydantic>=2.1.0",
    "pydantic-settings>=1.0.0",
]
